spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: qwertzui
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    show-sql: true
    redis:
      host: localhost
      port: 6379


